services:
  app:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ReBloom?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8mb4
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Rebloom@1234

      GMAIL_PASSWORD: ${GMAIL_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}

      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI: "http://3.35.21.19:8080/auth/login/google"
      JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF-8"
      LANG: ko_KR.UTF-8
      LC_ALL: ko_KR.UTF-8
      TZ: Asia/Seoul
    restart: always

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: Rebloom@1234
      MYSQL_DATABASE: ReBloom
    restart: always
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --init-connect="SET NAMES utf8mb4"
      --character-set-client-handshake=FALSE

volumes:
  db_data:
