name: CI/CD Docker Deploy

on:
  push:
    branches: [ "main", "feature/docker-backend" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        env:
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          envs: GMAIL_PASSWORD,GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET,JWT_SECRET
          script: |
            set -e
              
            if [ ! -d "rebloom-app" ]; then
            git clone https://github.com/${{ github.repository }}.git rebloom-app
            fi
            
            cd rebloom-app
            git fetch --all
            git reset --hard origin/main
            
            echo "GMAIL_PASSWORD=$GMAIL_PASSWORD" > .env
            echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" >> .env
            echo "GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET" >> .env
            echo "JWT_SECRET=$JWT_SECRET" >> .env
            
            docker compose down --remove-orphans  # ← 여기 핵심 추가!
            docker compose up -d --build
            docker image prune -a -f              # ← buildkit CACHED 이미지 포함 정리
