name: CI/CD Docker Deploy

on:
  push:
    branches: [ "main", "feature/docker-backend" ] # 작업중인 브랜치 포함

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        env:
          # [중요] 여기서 Secrets를 변수로 꺼내줘야 합니다!
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          # 위에서 만든 변수들을 가져간다고 명시
          envs: GMAIL_PASSWORD, GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, JWT_SECRET

          script: |
            if [ ! -d "rebloom-app" ]; then
              git clone https://github.com/${{ github.repository }}.git rebloom-app
            fi
            cd rebloom-app
            git pull origin main
            
            echo "GMAIL_PASSWORD=$GMAIL_PASSWORD" > .env
            echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" >> .env
            echo "GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET" >> .env
            echo "JWT_SECRET=$JWT_SECRET" >> .env
            
            docker compose down
            docker compose up -d --build
            docker image prune -f